LON-3220
ylatuya/lienzosharp pull request #21
Opened 2021-04-01 14:34 UTC by dfernandezramos

2021-04-01 14:35 UTC, dfernandezramos commented
DO NOT MERGE UNTIL https://github.com/ylatuya/lienzosharp/pull/20 approved and merged

2021-04-13 12:58 UTC, ylatuya requested changes

2021-04-13 12:58 UTC, ylatuya commented on src/LienzoSharp.Core/Shapes/Cross.cs
> +        public LineStyle LineStyle { get; set; }
Missing public documentation

2021-04-13 12:58 UTC, ylatuya commented on src/LienzoSharp.Core/Shapes/Ellipse.cs
> +        public LineStyle LineStyle { get; set; }
Missing documentation

2021-04-13 12:58 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/Utensils/ElipseUtensil.cs
> +            set => SetProperty(value, ref color, (d, v) =>
I would implement this differently. Since there is a single Color, I would override the setters and getters and setters of StrokeColor and FillColor to set and get the property Color.
Than in DrawScene I would implement that switch that changes the values of the ICanvas Fill and Stroke colors.
Otherwise, with the current implementation, a person could set FillColor on the Shape and everything would break.

2021-04-13 12:58 UTC, ylatuya commented on src/LienzoSharp.Core/Shapes/Rectangle.cs
> +        public LineStyle LineStyle { get; set; }
Missing public documentation

2021-04-15 16:04 UTC, ylatuya approved these changes

2021-04-16 09:51 UTC, ylatuya approved these changes
All good except for small comment

2021-04-16 09:51 UTC, ylatuya commented on src/LienzoSharp.Core/Shapes/Counter.cs
> +            canvas.StrokeColor = StrokeColor;
StrokeColor is set twice

2021-04-19 13:00 UTC, ylatuya requested changes

2021-04-20 15:12 UTC, merged