Add a toolbar to the drawing tool
ylatuya/lienzosharp pull request #25
Opened 2021-04-06 16:21 UTC by ylatuya

2021-04-07 16:13 UTC, dfernandezramos requested changes

2021-04-07 16:13 UTC, dfernandezramos commented on src/LienzoSharp.Skia/SkiaMatrix.cs
> +            return new SkiaMatrix(new SKMatrix(matrix.ScaleX, matrix.SkewX, matrix.TransX, matrix.SkewY, matrix.ScaleY, matrix.TransY, matrix.Persp0, matrix.Persp1, matrix.Persp2));
Why not cloning `this`? I assume this is just for performance? It will be faster creating a new instance rather than copying property by property. Am I correct?

2021-04-07 16:13 UTC, dfernandezramos commented on src/LienzoSharp.Tests/Utils.cs
>      public class MockedCanvas
Just for my curiosity. MockedCanvas would be called DummyCanvas in vasone, right? You are introducing here a new naming policy.

2021-04-07 16:13 UTC, dfernandezramos commented on src/LienzoSharp.Core/DrawingTool/UtensilsToolbar.cs
> +namespace LienzoSharp.DrawingTool
We should document this class

2021-04-07 16:54 UTC, ylatuya commented on src/SampleApp/SampleAppDemo.GTK/Program.cs
> +            LienzoSharp.Skia.GTK.ModuleInitializer.Initialize();
This. should be initialized automatically using Fody's ModuleInit weaver, but I have seen in several occasions that it's not happening, for example when launching the application with Xamarin Profiler. I haven't figured out why it happens, so for now I have re-instated the manual module initialization so it works with these corner cases.

2021-04-07 16:55 UTC, ylatuya commented on azure-pipelines.yml
> +- script: dotnet tool install dotnet-format --tool-path tools --version 4.1.131201
You might not need to. I had to go back to the previous release because the CI in Azure Pipelines was failing, the failure is in the commit message

2021-04-07 17:01 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/Utensils/UtensilBase.cs
> +                    if (CreationMode == CreationModeEnum.Drag || CreationMode == CreationModeEnum.MultipleClicks)
A transformer is a shape that allows transforming (resize/rotate, move) another shape. In a LienzoCanvas, when a node is selected, a new transformer for this node is created and added to the lienzo. In the case of a Rectangle a RectangleTransformer is created. This shape has 4 anchors in the corners of the rectangle that can be dragged to resize the rectangle.

2021-04-07 17:02 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/DrawingToolCanvas.cs
> +        internal DrawingToolCanvas(IView view, Lienzo lienzo) : this()
No one, that's the reason why it's internal. I didn't find a way to implement that test without this constructor (which might indicate a bad design in the API somewhere :P )

2021-04-07 17:10 UTC, ylatuya commented on src/LienzoSharp.Tests/Utils.cs
>      public class MockedCanvas
It's similar but not the same, DummyFoo is used for dummy implementations of abstract classes, it's usually DummyFoo: AbstractFoo. In this case, the class is a helper wrapper around a Mock<ICanvas>

2021-04-07 17:46 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/UtensilsToolbar.cs
> +namespace LienzoSharp.DrawingTool
Fixed

2021-04-07 20:28 UTC, ylatuya commented on src/LienzoSharp.Skia/SkiaMatrix.cs
> +            return new SkiaMatrix(new SKMatrix(matrix.ScaleX, matrix.SkewX, matrix.TransX, matrix.SkewY, matrix.ScaleY, matrix.TransY, matrix.Persp0, matrix.Persp1, matrix.Persp2));
We require a deep copy of the matrix, cloning serializes and de-serializes the object. It's useful for complex objects, but it this case it's easier creating a new instance

2021-04-08 06:47 UTC, dfernandezramos approved these changes

2021-04-08 07:54 UTC, merged