Lon 3230
ylatuya/lienzosharp pull request #27
Opened 2021-04-23 11:48 UTC by ylatuya

2021-04-23 19:21 UTC, dfernandezramos requested changes

2021-04-23 19:21 UTC, dfernandezramos commented on src/LienzoSharp.Core/DrawingTool/UtensilsToolbar.cs
> +        void DrawingToolCanvas_PropertyChanged(object sender, PropertyChangedEventArgs e)
Do you want to follow this naming rule for PropertyChanged methods or have you used the `_` by mistake?

2021-04-26 08:53 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/ControlsLayer.cs
> +        public UtensilsToolbar UtensilsWidget => utensilsToolbar;
It's not needed, the UtensilsWidget shouldn't be needed either, I am thinking of exposing the controls layer instead so that user can customize the whole controls and not only the utensils widget in case they need it

2021-04-26 13:16 UTC, dfernandezramos approved these changes

2021-04-26 15:39 UTC, merged