LON-3234
ylatuya/lienzosharp pull request #33
Opened 2021-05-13 10:29 UTC by dfernandezramos

2021-05-13 14:33 UTC, ylatuya requested changes
This PR tries to fix a serialization issue happening in an Utensil. The big question here, why is this happening at all? In DrawingToolCanvas.Save() we are only cloning the bakground layer and the images layer, no Utensil should be cloned at all.

2021-05-13 14:33 UTC, ylatuya commented on src/LienzoSharp.Core/Shapes/Path.cs
> +        public Path(RangeObservableCollection<Point> points)
Why is this changed needed at all? Even though internally we use a RangeObservableCollection, the constructor should take a List since its the most common structure to hold a list of values. I also don't think this change fixes anything in particular.

2021-05-13 14:33 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/Utensils/UtensilBase.cs
>          public DrawingToolCanvas DrawingToolCanvas { get; }
Does this property needs to be public at all?

2021-05-13 14:37 UTC, dfernandezramos commented on src/LienzoSharp.Core/DrawingTool/Utensils/UtensilBase.cs
>          public DrawingToolCanvas DrawingToolCanvas { get; }
I have not changed its accessor, but Ok. I will make it protected.

2021-05-13 14:40 UTC, dfernandezramos commented on src/LienzoSharp.Core/Shapes/Path.cs
> +        public Path(RangeObservableCollection<Point> points)
This change does fix the issue. Maybe you have in mind the Cursor error on serialization but this fixes another serialization issue regarding serializing a List into a RangeObservableCollection.

2021-05-13 14:55 UTC, ylatuya commented on src/LienzoSharp.Core/DrawingTool/Utensils/UtensilBase.cs
>          public DrawingToolCanvas DrawingToolCanvas { get; }
We need to investigate why the Utensil is serialized, as it shouldn't be at all.

2021-05-17 08:57 UTC, ylatuya commented on src/LienzoSharp.Core/Shapes/Line.cs
> +            (double StopX, double StopY) = BottomRight;
StopX StopY -> stopX stopY

2021-05-17 08:57 UTC, ylatuya approved these changes

2021-05-17 09:18 UTC, merged